linters:
  enable:
    - exhaustive
    - importas
    - gofmt
    - goimports
    - gosec
    - unused
    - tagliatelle
    - wastedassign

issues:
  exclude:
    - "Expect WriteFile permissions to be 0600 or less"
    - "Subprocess launched with a potential tainted input or cmd arguments"
