linters:
  enable:
    # Default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    # Additional
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - copyloopvar
    - decorder
    - dupword
    - durationcheck
    # Probably better to enable this, but too many existing errors.
    # - err113
    - errchkjson
    # Probably better to enable this, but too many existing errors.
    # - errname
    - exhaustive
    # Probably better to enable this, but too many existing errors.
    # - exhaustruct
    # Probably better to enable this, but too many existing errors.
    # - exptostd
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    # Probably better to enable this, but too many existing errors.
    # - gocritic
    - godot
    - gofmt
    - gofumpt
    - goimports
    - goprintffuncname
    # Probably better to enable this, but too many existing errors.
    # - gosec
    - iface
    - importas
    - intrange
    - makezero
    - mirror
    - misspell
    - noctx
    - nolintlint
    - nosprintfhostport
    - predeclared
    - reassign
    - recvcheck
    # Probably better to enable this, but too many existing errors.
    # - revive
    # Probably better to enable this, but too many existing errors.
    # - testifylint
    - thelper
    - unconvert
    # Probably better to enable this, but too many existing errors.
    # - unparam
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
