builds:
  - dir: "./cmd/av"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

# Create a GitHub release on the av repo
release: {}

# Push to the homebrew tap
brews:
  - tap:
      owner: aviator-co
      name: homebrew-tap
    commit_author:
      name: "aviator-bot"
      email: "105820887+aviator-bot@users.noreply.github.com"
    homepage: "https://aviator.co"
    license: "MIT"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
