before:
  hooks:
    - 'rm -rf man'
    - 'sh -c "cd docs && go run convert-manpages.go --output-dir ../man --version v{{ .Version }}"'

builds:
  - dir: "./cmd/av"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-X 'github.com/aviator-co/av/internal/config.Version=v{{ .Version }}'"

# Create a GitHub release on the av repo
release: {}

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "darwin" }}macos
      {{- else }}{{ .Arch }}{{ end }}
    files:
      - 'LICENSE'
      - 'README.md'
      - 'man'


# Push to the homebrew tap
brews:
  - tap:
      owner: aviator-co
      name: homebrew-tap
    commit_author:
      name: "aviator-bot"
      email: "105820887+aviator-bot@users.noreply.github.com"
    homepage: "https://aviator.co"
    license: "MIT"
    install: |
      bin.install "av"
      man.install Dir["man/*"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-dev-{{ .ShortCommit }}"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
