repos:
  - repo: local
    hooks:
      - id: goimports
        name: goimports
        files: ".+.go$"
        language: system
        entry: |
          sh -c 'go run golang.org/x/tools/cmd/goimports@latest -w .'
      - id: gofumpt
        name: gofumpt
        files: ".+.go$"
        language: system
        entry: |
          sh -c 'go run mvdan.cc/gofumpt@latest -l -w .'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'master']

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.33.0
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/zizmorcore/zizmor-pre-commit
    rev: v1.9.0
    hooks:
      - id: zizmor
