repos:
  - repo: local
    hooks:
      - id: golines
        name: golines
        files: ".+.go$"
        language: system
        entry: |
          sh -c 'go run github.com/segmentio/golines -w .'
      - id: goimports
        name: goimports
        files: ".+.go$"
        language: system
        entry: |
          sh -c 'go run golang.org/x/tools/cmd/goimports@latest -w .'

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: end-of-file-fixer
      - id: no-commit-to-branch
        args: ['--branch', 'master']

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.1
    hooks:
      - id: check-dependabot
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/woodruffw/zizmor-pre-commit
    rev: v1.3.1
    hooks:
      - id: zizmor
